#!/bin/sh

# /etc/X11/xinit/xinitrc
#
# global xinitrc file, used by all X sessions started by xinit (startx)
#export LC_ALL=zh_TW.UTF8
#export LANG=zh_TW.UTF8
export XMODIFIERS='@im=gcin'
export GTK_IM_MODULE="gcin"
export QT_IM_MODULE="gcin"
exec /usr/bin/gcin &

xrdb -merge ~/.Xresources

# invoke global X session script
. /etc/X11/Xsession

